### ISSUE TITLE
Import warehouses Error - не импортируются склады

### ISSUE THREAD

**Issue by yumicom** [yuriyakishin/novaposhta#1]
Модуль визуально довольно хорошо выполнен, аккуратно выглядит на чекауте, но есть проблемка:
Ошибка после magento novaposhta:data:import
.....
Import warehouses.

In ErrorHandler.php line 61:

  Notice: Undefined index: warehouse_id in .../app/code/Yu/NovaPoshta/Model/Import/WarehouseImport.php
   on line 65

Города нормально импортируются, проблема только со складами на Magento 2.3.2. 
Как импортировать склады? Может как то вручную можно?

**Comment by yuriyakishin** [comment]
Добрый день, спасибо за отзыв. Добавил лишнюю проверку, но по идее у вас должны были импортироваться склады все равно. Повторное применение команды
php bin/magento novaposhta:data:import
обновит данные о городах и складах. Также, если у вас настроен cron, то данные должны обновляться по крону.
Для проверки я подключил модуль на тестовом сайте http://shop.rp-studio.net/

**Comment by yuriyakishin** [comment]
Добрый день, спасибо за отзыв. Добавил лишнюю проверку, но по идее у вас
должны были импортироваться склады все равно. Повторное применение команды
php bin/magento novaposhta:data:import
обновит данные о городах и складах. Также, если у вас настроен cron, то
данные должны обновляться по крону.
Для проверки я подключил модуль на тестовом сайте http://shop.rp-studio.net/

сб, 18 янв. 2020 г. в 09:26, yumicom <notifications@github.com>:
