### ISSUE TITLE
Пожелания по доработке модуля

### ISSUE THREAD

**Issue by yumicom** [yuriyakishin/novaposhta#2]
Это не баг, а пожелания. 
На десктопе все ок, на мобиле не удобно. Дело в том, что на мобиле при выборе города пропадает поле поиска города и нет полосы прокрутки. А учитывая огромное количество городов, чтобы добраться даже до Киева надо оооочень долго работать пальчиком ))
Аналогичная проблемка при выборе отделения для больших городов - там их тоже немало в списке.
И еще бы добавить автовыбор первого отделения для всех городов.

**Comment by yuriyakishin** [comment]
Переделал, заменил модуль для селекта на другой.
